candidates:
  logreg:
    type: "logreg"
    params:
      max_iter: 500
  rf:
    type: "rf"
    params:
      n_estimators: 400
      n_jobs: -1
      random_state: 42
  gb:
    type: "gb"
    params:
      random_state: 42
selection_metric: "pr_auc"
specificity_target: 0.90
